language: node_js
node_js:
- "9"

install:
  - npm install -g codecov
  - cd Frontend
  - yarn install
  - cd ..
  - cd Backend
  - yarn install
  - cd ..

script:
  - codecov
  - cd Backend
  - yarn linter
  # - yarn test:ci
  - cd ..
  - cd Frontend
  - yarn build
  - yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION